
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMENT EXECUTE FDISK GUION IGUAL LOGIN LOGOUT MKDIR MKDISK MKFILE MKFS MKGRP MKUSR MOUNT NUMERO PALABRA REP RMDISK RMGRP RMUSR STRINGcmd : commandcmd : command param_listcommand : EXECUTEcommand : MKDISKcommand : RMDISKcommand : FDISKcommand : MOUNTcommand : MKFScommand : LOGINcommand : LOGOUTcommand : MKUSRcommand : RMUSRcommand : MKGRPcommand : RMGRPcommand : MKFILEcommand : MKDIRcommand : REPparam_list : paramparam_list : param_list paramparam : GUION PALABRAparam : GUION PALABRA IGUAL param_valueparam_value : PALABRA\n                   | STRING\n                   | NUMERO\n    '
    
_lr_action_items = {'EXECUTE':([0,],[3,]),'MKDISK':([0,],[4,]),'RMDISK':([0,],[5,]),'FDISK':([0,],[6,]),'MOUNT':([0,],[7,]),'MKFS':([0,],[8,]),'LOGIN':([0,],[9,]),'LOGOUT':([0,],[10,]),'MKUSR':([0,],[11,]),'RMUSR':([0,],[12,]),'MKGRP':([0,],[13,]),'RMGRP':([0,],[14,]),'MKFILE':([0,],[15,]),'MKDIR':([0,],[16,]),'REP':([0,],[17,]),'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,24,25,26,27,],[0,-1,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-2,-18,-19,-20,-22,-21,-23,-24,]),'GUION':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,24,25,26,27,],[20,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,20,-18,-19,-20,-22,-21,-23,-24,]),'PALABRA':([20,23,],[22,24,]),'IGUAL':([22,],[23,]),'STRING':([23,],[26,]),'NUMERO':([23,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmd':([0,],[1,]),'command':([0,],[2,]),'param_list':([2,],[18,]),'param':([2,18,],[19,21,]),'param_value':([23,],[25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmd","S'",1,None,None,None),
  ('cmd -> command','cmd',1,'p_cmd','parser.py',23),
  ('cmd -> command param_list','cmd',2,'p_cmd_params','parser.py',28),
  ('command -> EXECUTE','command',1,'p_command_execute','parser.py',35),
  ('command -> MKDISK','command',1,'p_command_mkdisk','parser.py',40),
  ('command -> RMDISK','command',1,'p_command_rmdisk','parser.py',45),
  ('command -> FDISK','command',1,'p_command_fdisk','parser.py',50),
  ('command -> MOUNT','command',1,'p_command_mount','parser.py',55),
  ('command -> MKFS','command',1,'p_command_mkfs','parser.py',60),
  ('command -> LOGIN','command',1,'p_command_login','parser.py',65),
  ('command -> LOGOUT','command',1,'p_command_logout','parser.py',70),
  ('command -> MKUSR','command',1,'p_command_mkusr','parser.py',75),
  ('command -> RMUSR','command',1,'p_command_rmusr','parser.py',80),
  ('command -> MKGRP','command',1,'p_command_mkgrp','parser.py',85),
  ('command -> RMGRP','command',1,'p_command_rmgrp','parser.py',90),
  ('command -> MKFILE','command',1,'p_command_mkfile','parser.py',95),
  ('command -> MKDIR','command',1,'p_command_mkdir','parser.py',100),
  ('command -> REP','command',1,'p_command_rep','parser.py',105),
  ('param_list -> param','param_list',1,'p_param_list','parser.py',111),
  ('param_list -> param_list param','param_list',2,'p_param_list_r','parser.py',116),
  ('param -> GUION PALABRA','param',2,'p_param','parser.py',122),
  ('param -> GUION PALABRA IGUAL param_value','param',4,'p_param_v','parser.py',127),
  ('param_value -> PALABRA','param_value',1,'p_param_value','parser.py',132),
  ('param_value -> STRING','param_value',1,'p_param_value','parser.py',133),
  ('param_value -> NUMERO','param_value',1,'p_param_value','parser.py',134),
]
